/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Music } from "./Music";
import { MusicCountArgs } from "./MusicCountArgs";
import { MusicFindManyArgs } from "./MusicFindManyArgs";
import { MusicFindUniqueArgs } from "./MusicFindUniqueArgs";
import { CreateMusicArgs } from "./CreateMusicArgs";
import { UpdateMusicArgs } from "./UpdateMusicArgs";
import { DeleteMusicArgs } from "./DeleteMusicArgs";
import { RecommendationFindManyArgs } from "../../recommendation/base/RecommendationFindManyArgs";
import { Recommendation } from "../../recommendation/base/Recommendation";
import { MusicService } from "../music.service";
@graphql.Resolver(() => Music)
export class MusicResolverBase {
  constructor(protected readonly service: MusicService) {}

  async _musicItemsMeta(
    @graphql.Args() args: MusicCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Music])
  async musicItems(@graphql.Args() args: MusicFindManyArgs): Promise<Music[]> {
    return this.service.musicItems(args);
  }

  @graphql.Query(() => Music, { nullable: true })
  async music(
    @graphql.Args() args: MusicFindUniqueArgs
  ): Promise<Music | null> {
    const result = await this.service.music(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Music)
  async createMusic(@graphql.Args() args: CreateMusicArgs): Promise<Music> {
    return await this.service.createMusic({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Music)
  async updateMusic(
    @graphql.Args() args: UpdateMusicArgs
  ): Promise<Music | null> {
    try {
      return await this.service.updateMusic({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Music)
  async deleteMusic(
    @graphql.Args() args: DeleteMusicArgs
  ): Promise<Music | null> {
    try {
      return await this.service.deleteMusic(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Recommendation], { name: "recommendations" })
  async findRecommendations(
    @graphql.Parent() parent: Music,
    @graphql.Args() args: RecommendationFindManyArgs
  ): Promise<Recommendation[]> {
    const results = await this.service.findRecommendations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.Query(() => String)
  async CatalogMusic(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.CatalogMusic(args);
  }

  @graphql.Mutation(() => Music)
  async CatalogMusicTrack(
    @graphql.Args()
    args: CreateMusicArgs
  ): Promise<Music> {
    return this.service.CatalogMusicTrack(args);
  }

  @graphql.Query(() => String)
  async CatalogNewMusic(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.CatalogNewMusic(args);
  }
}
